import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "outline-variant": "#d4c3be",
        "secondary-fixed-dim": "#cfc4c0",
        "on-surface": "#1e1c10",
        "secondary-fixed": "#ece0dc",
        "on-secondary-fixed-variant": "#4c4542",
        "inverse-on-surface": "#f7f0dd",
        tertiary: "#273604",
        "primary-container": "#5d4037",
        surface: "#fff9ec",
        "secondary-container": "#ece0dc",
        primary: "#442a22",
        "inverse-primary": "#e7bdb1",
        outline: "#827470",
        "on-secondary-fixed": "#201a18",
        "on-background": "#1e1c10",
        "on-tertiary-fixed-variant": "#3c4c18",
        "on-tertiary-container": "#a9be7d",
        "on-secondary-container": "#6b6360",
        "on-primary-fixed": "#2c160e",
        "tertiary-container": "#3c4d19",
        error: "#ba1a1a",
        "on-surface-variant": "#504441",
        "on-tertiary": "#ffffff",
        "surface-tint": "#77574d",
        "surface-dim": "#e0dac7",
        "surface-bright": "#fff9ec",
        "primary-fixed": "#ffdbd0",
        "inverse-surface": "#333024",
        "surface-container-low": "#faf3e0",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#e7bdb1",
        "tertiary-fixed-dim": "#bace8c",
        "surface-container": "#f4eedb",
        "surface-container-highest": "#e9e2d0",
        "surface-container-high": "#efe8d5",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        background: "#fff9ec",
        secondary: "#655d5a",
        "on-primary-fixed-variant": "#5d4037",
        "tertiary-fixed": "#d6eba6",
        "on-tertiary-fixed": "#141f00",
        "on-primary-container": "#d4ada1",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-variant": "#e9e2d0",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {},
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [],
} satisfies Config;

export default config